# github.com/Shran21
from __future__ import annotations

from rebsgo.native.hotpath import (
    candidate_pairs_from_cells,
    encode_combat_info_packet,
    encode_object_left_ids_packet,
    encode_weapon_shot_packet,
    filter_aabb_ids,
    filter_out_of_bounds_ids,
    filter_radius_ids,
    filter_range_distance_sq,
    filter_sphere_pair_indices,
    future_positions,
    is_native_available,
    is_native_radius_filter_enabled,
    log_native_event,
    native_diagnostics_enabled,
    native_status,
    nearest_radius_id,
    should_use_native_nearest_radius,
    should_use_native_out_of_bounds_filter,
    should_use_native_future_positions,
    should_use_native_packet_serialization,
    should_use_native_range_distance,
    should_use_native_spatial_filter,
    should_use_native_spatial_pair_generation,
    should_use_native_radius_filter,
    should_use_native_sphere_pair_filter,
)

__all__ = [
    "candidate_pairs_from_cells",
    "encode_combat_info_packet",
    "encode_object_left_ids_packet",
    "encode_weapon_shot_packet",
    "filter_aabb_ids",
    "filter_out_of_bounds_ids",
    "filter_radius_ids",
    "filter_range_distance_sq",
    "filter_sphere_pair_indices",
    "future_positions",
    "is_native_available",
    "is_native_radius_filter_enabled",
    "log_native_event",
    "native_diagnostics_enabled",
    "native_status",
    "nearest_radius_id",
    "should_use_native_nearest_radius",
    "should_use_native_out_of_bounds_filter",
    "should_use_native_future_positions",
    "should_use_native_packet_serialization",
    "should_use_native_range_distance",
    "should_use_native_spatial_filter",
    "should_use_native_spatial_pair_generation",
    "should_use_native_radius_filter",
    "should_use_native_sphere_pair_filter",
]
